version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-api
    ports:
      - "8080:8080"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./alert.rules.yml:/etc/prometheus/alert.rules.yml  # Remova se não estiver usando
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitor-net
    depends_on:
      - prometheus

volumes:
  grafana-storage:

networks:
  monitor-net:
    driver: bridge
