# application.yml

# 🚀 Configurações do Servidor Web
server:
  port: 8080 # Porta padrão para a sua API

# 🗄️ Configurações do Banco de Dados H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 🛠️ Spring DevTools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# 🔒 JWT
jwt:
  secret: umaChaveSecretaMuitoLongaEComplexaParaAssinarTokensJWT
  expiration: 3600000

# 📚 Swagger OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

# 📊 Spring Boot Actuator e Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus # Expor os endpoints desejados
      base-path: /actuator # Caminho base dos endpoints (ex: /actuator/health)
  endpoint:
    health:
      show-details: always # Mostra detalhes no /health (como banco de dados, etc.)
